-- Create objective_action_plans table
-- Stores AI-generated action plans for failed objectives

CREATE TABLE IF NOT EXISTS objective_action_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  objective_id UUID NOT NULL REFERENCES company_objectives(id) ON DELETE CASCADE,
  year INTEGER NOT NULL,
  timespan TEXT NOT NULL CHECK (timespan IN ('q1', 'q2', 'q3', 'q4', 'all')),
  plan TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(objective_id, year, timespan)
);

COMMENT ON TABLE objective_action_plans IS 'AI-generated action plans for failed objectives';
COMMENT ON COLUMN objective_action_plans.objective_id IS 'Reference to the objective this plan is for';
COMMENT ON COLUMN objective_action_plans.year IS 'Year the plan was generated for';
COMMENT ON COLUMN objective_action_plans.timespan IS 'Timespan (q1, q2, q3, q4, all) the plan was generated for';
COMMENT ON COLUMN objective_action_plans.plan IS 'Markdown-formatted action plan generated by AI';

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_objective_action_plans_objective_year_timespan 
  ON objective_action_plans(objective_id, year, timespan);

