-- Seed all Zembra supported platforms
-- Based on https://zembratech.com/supported-platforms/

-- Default descriptions
DO $$
DECLARE
  default_desc_en TEXT := 'Find the slug in your platform URL';
  default_desc_fr TEXT := 'Trouvez le slug dans l''URL de votre plateforme';
BEGIN
  -- Insert all platforms from Zembra's supported platforms list
  INSERT INTO supported_platforms (name, display_name, description_en, description_fr, base_url, is_active) VALUES
    ('abritel', 'Abritel', default_desc_en, default_desc_fr, 'https://www.abritel.fr', true),
    ('agoda', 'Agoda', default_desc_en, default_desc_fr, 'https://www.agoda.com', true),
    ('airbnb', 'Airbnb', default_desc_en, default_desc_fr, 'https://www.airbnb.com', true),
    ('alternativeto', 'AlternativeTo', default_desc_en, default_desc_fr, 'https://alternativeto.net', true),
    ('angi', 'Angi', default_desc_en, default_desc_fr, 'https://www.angi.com', true),
    ('apartment-guide', 'Apartment Guide', default_desc_en, default_desc_fr, 'https://www.apartmentguide.com', true),
    ('apartmentratings', 'ApartmentRatings', default_desc_en, default_desc_fr, 'https://www.apartmentratings.com', true),
    ('apartments-com', 'Apartments.com', default_desc_en, default_desc_fr, 'https://www.apartments.com', true),
    ('app-store', 'App Store', default_desc_en, default_desc_fr, 'https://www.apple.com/app-store', true),
    ('apple-maps', 'Apple Maps', default_desc_en, default_desc_fr, 'https://www.apple.com/maps', true),
    ('autotrader', 'Autotrader', default_desc_en, default_desc_fr, 'https://www.autotrader.com', true),
    ('avvo', 'Avvo', default_desc_en, default_desc_fr, 'https://www.avvo.com', true),
    ('bbb', 'Better Business Bureau', default_desc_en, default_desc_fr, 'https://www.bbb.org', true),
    ('bing', 'Bing', default_desc_en, default_desc_fr, 'https://www.bing.com', true),
    ('bol', 'Bol', default_desc_en, default_desc_fr, 'https://www.bol.com', true),
    ('bookabach', 'Bookabach', default_desc_en, default_desc_fr, 'https://www.bookabach.co.nz', true),
    ('booking', 'Booking', default_desc_en, default_desc_fr, 'https://www.booking.com', true),
    ('capterra', 'Capterra', default_desc_en, default_desc_fr, 'https://www.capterra.com', true),
    ('carfax', 'Carfax', default_desc_en, default_desc_fr, 'https://www.carfax.com', true),
    ('cars', 'Cars', default_desc_en, default_desc_fr, 'https://www.cars.com', true),
    ('carvana', 'Carvana', default_desc_en, default_desc_fr, 'https://www.carvana.com', true),
    ('citysearch', 'City Search', default_desc_en, default_desc_fr, 'https://www.citysearch.com', true),
    ('classpass', 'ClassPass', default_desc_en, default_desc_fr, 'https://classpass.com', true),
    ('clutch', 'Clutch', default_desc_en, default_desc_fr, 'https://clutch.co', true),
    ('consumeraffairs', 'ConsumerAffairs', default_desc_en, default_desc_fr, 'https://www.consumeraffairs.com', true),
    ('creditkarma', 'CreditKarma', default_desc_en, default_desc_fr, 'https://www.creditkarma.com', true),
    ('dealerrater', 'DealerRater', default_desc_en, default_desc_fr, 'https://www.dealerrater.com', true),
    ('designmynight', 'DesignMyNight', default_desc_en, default_desc_fr, 'https://www.designmynight.com', true),
    ('doctor', 'Doctor', default_desc_en, default_desc_fr, 'https://www.doctor.com', true),
    ('doordash', 'DoorDash', default_desc_en, default_desc_fr, 'https://www.doordash.com', true),
    ('etsy', 'Etsy', default_desc_en, default_desc_fr, 'https://www.etsy.com', true),
    ('expedia', 'Expedia', default_desc_en, default_desc_fr, 'https://www.expedia.com', true),
    ('facebook', 'Facebook', 'Find your Page ID in Page Settings > About', 'Trouvez votre ID de page dans Paramètres de la page > À propos', 'https://www.facebook.com', true),
    ('fertilityiq', 'FertilityIQ', default_desc_en, default_desc_fr, 'https://www.fertilityiq.com', true),
    ('fewo-direkt', 'FeWo-Direkt', default_desc_en, default_desc_fr, 'https://www.fewo-direkt.de', true),
    ('findlaw', 'FindLaw', default_desc_en, default_desc_fr, 'https://www.findlaw.com', true),
    ('flipkart', 'Flipkart', default_desc_en, default_desc_fr, 'https://www.flipkart.com', true),
    ('foursquare', 'Foursquare', default_desc_en, default_desc_fr, 'https://foursquare.com', true),
    ('gartner', 'Gartner', default_desc_en, default_desc_fr, 'https://www.gartner.com', true),
    ('glassdoor', 'Glassdoor', default_desc_en, default_desc_fr, 'https://www.glassdoor.com', true),
    ('goibibo', 'Goibibo', default_desc_en, default_desc_fr, 'https://www.goibibo.com', true),
    ('goodreads', 'Goodreads', default_desc_en, default_desc_fr, 'https://www.goodreads.com', true),
    ('google', 'Google', 'Use Google Place ID Finder or find in Google My Business URL', 'Utilisez le rechercheur d''ID de lieu Google ou trouvez-le dans l''URL Google My Business', 'https://www.google.com/maps', true),
    ('google-local-services-ads', 'Google Local Services Ads', default_desc_en, default_desc_fr, 'https://ads.google.com/local-services', true),
    ('google-play', 'Google Play', default_desc_en, default_desc_fr, 'https://play.google.com', true),
    ('greatschools', 'GreatSchools', default_desc_en, default_desc_fr, 'https://www.greatschools.org', true),
    ('grubhub', 'Grubhub', default_desc_en, default_desc_fr, 'https://www.grubhub.com', true),
    ('healthgrades', 'Healthgrades', default_desc_en, default_desc_fr, 'https://www.healthgrades.com', true),
    ('homeadvisor', 'HomeAdvisor', default_desc_en, default_desc_fr, 'https://www.homeadvisor.com', true),
    ('houzz', 'Houzz', default_desc_en, default_desc_fr, 'https://www.houzz.com', true),
    ('indeed', 'Indeed', default_desc_en, default_desc_fr, 'https://www.indeed.com', true),
    ('influenster', 'Influenster', default_desc_en, default_desc_fr, 'https://www.influenster.com', true),
    ('insiderpages', 'InsiderPages', default_desc_en, default_desc_fr, 'https://www.insiderpages.com', true),
    ('instagram', 'Instagram', default_desc_en, default_desc_fr, 'https://www.instagram.com', true),
    ('justeat', 'Just Eat', default_desc_en, default_desc_fr, 'https://www.justeat.co.uk', true),
    ('justdial', 'JustDial', default_desc_en, default_desc_fr, 'https://www.justdial.com', true),
    ('kayak', 'Kayak', default_desc_en, default_desc_fr, 'https://www.kayak.com', true),
    ('kelley-blue-book', 'Kelley Blue Book', default_desc_en, default_desc_fr, 'https://www.kbb.com', true),
    ('lawyers', 'Lawyers', default_desc_en, default_desc_fr, 'https://www.lawyers.com', true),
    ('lendingtree', 'LendingTree', default_desc_en, default_desc_fr, 'https://www.lendingtree.com', true),
    ('lieferando', 'Lieferando', default_desc_en, default_desc_fr, 'https://www.lieferando.de', true),
    ('linkedin', 'LinkedIn', default_desc_en, default_desc_fr, 'https://www.linkedin.com', true),
    ('makemytrip', 'MakeMyTrip', default_desc_en, default_desc_fr, 'https://www.makemytrip.com', true),
    ('niche', 'Niche', default_desc_en, default_desc_fr, 'https://www.niche.com', true),
    ('opentable', 'OpenTable', 'Found in your restaurant URL or OpenTable settings', 'Trouvé dans l''URL de votre restaurant ou les paramètres OpenTable', 'https://www.opentable.com', true),
    ('orbitz', 'Orbitz', default_desc_en, default_desc_fr, 'https://www.orbitz.com', true),
    ('pagesjaunes', 'PagesJaunes', default_desc_en, default_desc_fr, 'https://www.pagesjaunes.fr', true),
    ('practo', 'Practo', default_desc_en, default_desc_fr, 'https://www.practo.com', true),
    ('producthunt', 'Product Hunt', default_desc_en, default_desc_fr, 'https://www.producthunt.com', true),
    ('productreview', 'Product Review', default_desc_en, default_desc_fr, 'https://www.productreview.com.au', true),
    ('ratemds', 'RateMDs', default_desc_en, default_desc_fr, 'https://www.ratemds.com', true),
    ('realself', 'RealSelf', default_desc_en, default_desc_fr, 'https://www.realself.com', true),
    ('reddit', 'Reddit', default_desc_en, default_desc_fr, 'https://www.reddit.com', true),
    ('rent', 'Rent', default_desc_en, default_desc_fr, 'https://www.rent.com', true),
    ('resellerratings', 'ResellerRatings', default_desc_en, default_desc_fr, 'https://www.resellerratings.com', true),
    ('sitejabber', 'Sitejabber', default_desc_en, default_desc_fr, 'https://www.sitejabber.com', true),
    ('smyths-toys', 'Smyths toys', default_desc_en, default_desc_fr, 'https://www.smythstoys.com', true),
    ('softwareadvice', 'Software Advice', default_desc_en, default_desc_fr, 'https://www.softwareadvice.com', true),
    ('stayz', 'Stayz', default_desc_en, default_desc_fr, 'https://www.stayz.com.au', true),
    ('steam', 'Steam', default_desc_en, default_desc_fr, 'https://store.steampowered.com', true),
    ('supermoney', 'SuperMoney', default_desc_en, default_desc_fr, 'https://www.supermoney.com', true),
    ('takeaway', 'Takeaway', default_desc_en, default_desc_fr, 'https://www.takeaway.com', true),
    ('talabat', 'Talabat', default_desc_en, default_desc_fr, 'https://www.talabat.com', true),
    ('target', 'Target', default_desc_en, default_desc_fr, 'https://www.target.com', true),
    ('the-knot', 'The Knot', default_desc_en, default_desc_fr, 'https://www.theknot.com', true),
    ('thefork', 'TheFork', default_desc_en, default_desc_fr, 'https://www.thefork.com', true),
    ('thuisbezorgd', 'Thuisbezorgd', default_desc_en, default_desc_fr, 'https://www.thuisbezorgd.nl', true),
    ('tiktok', 'TikTok', default_desc_en, default_desc_fr, 'https://www.tiktok.com', true),
    ('travelocity', 'Travelocity', default_desc_en, default_desc_fr, 'https://www.travelocity.com', true),
    ('treatwell', 'Treatwell', default_desc_en, default_desc_fr, 'https://www.treatwell.co.uk', true),
    ('tripadvisor', 'TripAdvisor', 'Found in your location URL (e.g., tripadvisor.com/Restaurant_Review...)', 'Trouvé dans l''URL de votre emplacement (ex. : tripadvisor.com/Restaurant_Review...)', 'https://www.tripadvisor.com', true),
    ('trustpilot', 'Trustpilot', default_desc_en, default_desc_fr, 'https://www.trustpilot.com', true),
    ('trustradius', 'TrustRadius', default_desc_en, default_desc_fr, 'https://www.trustradius.com', true),
    ('ubereats', 'UberEats', default_desc_en, default_desc_fr, 'https://www.ubereats.com', true),
    ('vitals', 'Vitals', default_desc_en, default_desc_fr, 'https://www.vitals.com', true),
    ('vrbo', 'Vrbo', default_desc_en, default_desc_fr, 'https://www.vrbo.com', true),
    ('webmd', 'WebMD', default_desc_en, default_desc_fr, 'https://www.webmd.com', true),
    ('weddingwire', 'WeddingWire', default_desc_en, default_desc_fr, 'https://www.weddingwire.com', true),
    ('yell', 'Yell', default_desc_en, default_desc_fr, 'https://www.yell.com', true),
    ('yellow-pages', 'Yellow Pages', default_desc_en, default_desc_fr, 'https://www.yellowpages.com', true),
    ('yelp', 'Yelp', 'Found in your business URL: yelp.com/biz/[business-id]', 'Trouvé dans l''URL de votre entreprise : yelp.com/biz/[business-id]', 'https://www.yelp.com', true),
    ('zillow', 'Zillow', default_desc_en, default_desc_fr, 'https://www.zillow.com', true),
    ('zocdoc', 'ZocDoc', default_desc_en, default_desc_fr, 'https://www.zocdoc.com', true),
    ('zomato', 'Zomato', default_desc_en, default_desc_fr, 'https://www.zomato.com', true)
  ON CONFLICT (name) DO NOTHING;
END $$;







