-- Add generation_type column to action_plan_items table
-- This tracks whether an item was generated by AI or created manually by a user

ALTER TABLE action_plan_items
ADD COLUMN generation_type TEXT NOT NULL DEFAULT 'ai' CHECK (generation_type IN ('ai', 'manual'));

COMMENT ON COLUMN action_plan_items.generation_type IS 'How the item was generated: ai or manual';

